#!/usr/bin/env python3

import logging
from sysview.common.utils import get_config
from sysview.common.cache import get_cache
from sysview.client.client import get_parser

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()

    if args.verbose >= 2:
        loglevel = logging.DEBUG
    elif args.verbose == 1:
        loglevel = logging.INFO
    else:
        loglevel = logging.WARNING

    logging.basicConfig(
        level=loglevel,
        format='%(levelname)s %(module)s.%(funcName)s(): %(message)s'
    )
    logger = logging.getLogger(__name__)

    logger.info('Logger level: %d' % logger.getEffectiveLevel())

    config = get_config(args.config_file)
    cache = get_cache(args=args, config=config)

    try:
        args.func(args=args, cache=cache)
    except AttributeError as e:
        print(e)
        parser.print_help()

